image: multiversa/gitpod-php:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Nginx
    init: echo 'Init workspace'
    env:
      NGINX_DOCROOT_IN_REPO: 'public'
    command: |
      sudo nginx &&
      multitail -f /var/log/nginx/access.log -I /var/log/nginx/error.log
  - name: Console

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 80 for the frontend
    port: 80
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
