image: multiversa/gitpod-php:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Start Terminal
    init: echo 'Init workspace'
    command: sudo service nginx start
  - name: Normal Terminal
    command: >
      date

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 80 for the frontend
    port: 80
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
